CREATE TABLE ACCOUNT(
	ID VARCHAR (36) PRIMARY KEY,
	NAME VARCHAR (200) NOT NULL,
	EMAIL VARCHAR (50) UNIQUE NOT NULL,
	PASSWORD VARCHAR (200) NOT NULL,
	BALANCE NUMERIC NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL
);