CREATE TABLE ACCOUNT_TRANSACTION (
  ID VARCHAR (36) PRIMARY KEY,
  ACCOUNT_ID VARCHAR (36) REFERENCES ACCOUNT(ID) NOT NULL,
  TYPE VARCHAR(50) NOT NULL,
  VALUE NUMERIC NOT NULL,
  CREATED_ON TIMESTAMP NOT NULL
);