CREATE TABLE BITCOIN_INVESTMENT (
  ID VARCHAR (36) PRIMARY KEY,
  ACCOUNT_ID VARCHAR (36) REFERENCES ACCOUNT(ID) NOT NULL,
  INVESTED_AMOUNT NUMERIC NOT NULL,
  BITCOIN_VALUE_AT_THE_TIME_OF_PURCHASE NUMERIC NOT NULL,
  BITCOIN_AMOUNT NUMERIC NOT NULL,
  CREATED_ON TIMESTAMP NOT NULL
);